name: aceverify
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - matplotlib-inline
  - pydantic
  - requests
  - tqdm
  - pyyaml
  - pillow
  - numpy
  - scipy
  - matplotlib
  - h5py
  - pip:
      - torch
      - torchvision
      - torchaudio
      - facenet-pytorch
      - ffmpeg-python
      - huggingface-hub
      - scikit-learn
      - timm
      - sqlalchemy
      - dataset
      - alembic
      - opencv-python-headless
      - mediapipe
      - streamlit